name: API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install pipenv
          pipenv install fastapi uvicorn pytest requests

      - name: Start FastAPI server
        run: |
          pipenv run python apiserver.py &
        env:
          PYTHONUNBUFFERED: 1

      - name: Wait for server to be ready
        run: sleep 5

      - name: List test files
        run: ls -l devops-test-automation-main

      - name: Run tests
        run: pipenv run pytest devops-test-automation-main/automation_test_pytest.py
